/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2019-09-05 19:09:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import animais.*;

public final class Animais_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");


if(request.getParameter("tamanho") != null && request.getParameter("nome") != null){
	Cachorro cao;
	Gato gato;
	
	float tamanho = Float.parseFloat(request.getParameter("tamanho"));
	String nome = request.getParameter("nome");
	int tipo = Integer.parseInt(request.getParameter("tipo"));
	
	if(tipo==1) {
		int unha = Integer.parseInt(request.getParameter("unha"));
		cao = new Cachorro(tamanho, nome, unha);
		response.getWriter().append("Tipo: Cachorro<br>Nome: " + cao.getNome() +"<br>");
		response.getWriter().append("Tamanho: " + cao.getTamanho() +"<br>");
		response.getWriter().append("Unhas: " + cao.getUnhas() +"<br>");
		
		response.getWriter().append("<br>" + cao.andar() +"<br>");
	}else if(tipo==2) {
		int vidas = Integer.parseInt(request.getParameter("vida"));
		gato = new Gato(tamanho, nome, vidas);
		response.getWriter().append("Tipo: Gato<br>Nome: " + gato.getNome() +"<br>");
		response.getWriter().append("Tamanho: " + gato.getTamanho() +"<br>");
		response.getWriter().append("Vidas: " + gato.getVidas() +"<br>");
	}
}else{

      out.write("\r\n");
      out.write("<form action=\"Animais.jsp\" method=\"get\">\r\n");
      out.write("\t<label>Nome:</label><input name=\"nome\" type=\"text\"><br>\r\n");
      out.write("\t<label>Tamanho:</label><input name=\"tamanho\" type=\"text\"><br>\r\n");
      out.write("\t<label>Tipo de animal</label><br>\r\n");
      out.write("\t<input name=\"tipo\" type=\"radio\" value=\"1\"><label>Cachorro</label><br>\r\n");
      out.write("\t<input name=\"tipo\" type=\"radio\" value=\"2\"><label>Gato</label><br><br>\r\n");
      out.write("\t<label>N° de unhas(para cachorro):</label><input name=\"unha\" type=\"number\"><br><br>\r\n");
      out.write("\t<label>N° de vidas(para gato):</label><input name=\"vida\" type=\"number\"><br><br>\r\n");
      out.write("\t<input type=\"submit\" name=\"Enviar\">\r\n");
      out.write("</form>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
