/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2019-09-12 20:25:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DTO.ProdutoDto;

public final class produto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	ProdutoDto pessoa = new ProdutoDto();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

if(request.getParameter("nome") != null && request.getParameter("idFor") != null){
	pessoa.setNomeProduto(request.getParameter("nome"));
	pessoa.setIdFornecedor(Integer.parseInt(request.getParameter("idFor")));
	pessoa.setIdCategoria(Integer.parseInt(request.getParameter("idCat")));
	pessoa.setQuantidadePorUnidade(request.getParameter("qtdUni"));
	pessoa.setPrecoUnitario(Double.parseDouble(request.getParameter("precoUni")));
	pessoa.setUnidadesEmEstoque(Integer.parseInt(request.getParameter("UniEst")));
	pessoa.setUnidadesEmOrdem(Integer.parseInt(request.getParameter("UniOrd")));
	pessoa.setNivelDeReposicao(Integer.parseInt(request.getParameter("NivelRep")));
	//pessoa.setNivelDeReposicao(request.getParameter("dataNasc"));
	if(request.getParameter("desc") == "1"){
		pessoa.setDescontinuado(true);
	}else{
		pessoa.setDescontinuado(false);
	}
}else{

      out.write("\r\n");
      out.write("<form action=\"produto.jsp\" method=\"get\">\r\n");
      out.write("\t<label>Nome do Produto:</label><input name=\"nome\" type=\"text\"><br>\r\n");
      out.write("\t<label>Id do fornecedor:</label><input name=\"idFor\" type=\"number\"><br>\r\n");
      out.write("\t<label>Id da categoria:</label><input name=\"idCat\" type=\"number\"><br>\r\n");
      out.write("\t<label>Quantidade por unidade:</label><input name=\"qtdUni\" type=\"text\"><br>\r\n");
      out.write("\t<label>Preço unitario:</label><input name=\"precoUni\" type=\"text\"><br>\r\n");
      out.write("\t<label>Unidades em estoque:</label><input name=\"UniEst\" type=\"number\"><br>\r\n");
      out.write("\t<label>Unidades em ordem:</label><input name=\"UniOrd\" type=\"number\"><br>\r\n");
      out.write("\t<label>Nivel de reposição:</label><input name=\"NivelRep\" type=\"text\"><br>\r\n");
      out.write("\t<label>Descontinuado?</label><br>\r\n");
      out.write("\t<input name=\"desc\" type=\"radio\" value=\"1\"><label>Sim</label><br>\r\n");
      out.write("\t<input name=\"desc\" type=\"radio\" value=\"0\"><label>Não</label><br>\r\n");
      out.write("\t<input type=\"submit\" name=\"Enviar\">\r\n");
      out.write("</form>\r\n");
 } 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
